trigger:
  - main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageRepository: build-oiio
  dockerFilePath: Dockerfile
  dockerRegistryServiceConnection: dockerhub/rhaleblian
  tag: latest

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)
